[tool.poetry]
name = "web-scrapper-ai-agent"
version = "0.1.0"
description = ""
authors = ["Ramanjit Singh <ramanjit.singh@sifars.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
